# Generated by stump.wtf/cairn's release pipeline (the tap-bump job) from
# packaging/homebrew/cairn.rb.tmpl in https://github.com/stump-wtf/cairn.
# Edit the template there, not this file: the next release overwrites it.
class Cairn < Formula
  # A Binary Formula, Not A Build-From-Source One
  #
  # Every other formula in this tap (harness, msgbrowse, reduit) compiles from a
  # public source tarball. cairn pins prebuilt binaries instead, four url/sha256
  # pairs installed directly, so installing needs no Go toolchain. The release
  # path is built around that: a v* tag publishes cross-platform archives to
  # github.com/stump-wtf/cairn (binaries only), and the tap-bump job renders
  # this file from those assets.
  #
  # The urls carry the version literally, with no separate `version` line.
  # `brew audit --strict` rejects a `version` that the url already implies, and
  # rendering the whole file means there is no line to keep in sync.
  #
  # Assets come from GitHub, never the canonical Gitea host, which is reachable
  # only on its own network: a Gitea-hosted download hangs for everyone else.
  desc "Share files, logs, and diffs as short links with provenance and a TTL"
  homepage "https://cairn.stump.wtf"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.3.0/cairn_0.3.0_darwin_arm64.tar.gz"
      sha256 "21767780a49f7dd58666aadad44e4174ca733f0737df3bd34639683a97e3c069"
    end
    on_intel do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.3.0/cairn_0.3.0_darwin_amd64.tar.gz"
      sha256 "26a07e00e32aba96635efdd453fb958ee30488a64bfd9e2135cdd6e33ff6c091"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.3.0/cairn_0.3.0_linux_arm64.tar.gz"
      sha256 "41fc0a367fa01de56f30389fb9a47f28bf16164f6a4764bb85e04fff61a699d2"
    end
    on_intel do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.3.0/cairn_0.3.0_linux_amd64.tar.gz"
      sha256 "5e3916eaa6d4b494b6eddc4f3d976fedafebeef0903690a73ef549df9af7eb2c"
    end
  end

  def install
    # The archive holds exactly `cairn` and `LICENSE` at its root
    # (.goreleaser.yaml pins archives.files to [LICENSE] and leaves
    # wrap_in_directory off), so name the binary rather than globbing: a glob
    # would install LICENSE into bin/ as though it were a program.
    bin.install "cairn"
  end

  test do
    # goreleaser stamps the version with no leading "v", so `cairn --version`
    # prints the bare version.
    assert_match version.to_s, shell_output("#{bin}/cairn --version")
  end
end
