# Generated by stump.wtf/cairn's release pipeline (the tap-bump job) from
# packaging/homebrew/cairn.rb.tmpl in https://github.com/stump-wtf/cairn.
# Edit the template there, not this file: the next release overwrites it.
class Cairn < Formula
  # A Binary Formula, Not A Build-From-Source One
  #
  # Every other formula in this tap (harness, msgbrowse, reduit) compiles from a
  # public source tarball. cairn pins prebuilt binaries instead, four url/sha256
  # pairs installed directly, so installing needs no Go toolchain. The release
  # path is built around that: a v* tag publishes cross-platform archives to
  # github.com/stump-wtf/cairn (binaries only), and the tap-bump job renders
  # this file from those assets.
  #
  # The urls carry the version literally, with no separate `version` line.
  # `brew audit --strict` rejects a `version` that the url already implies, and
  # rendering the whole file means there is no line to keep in sync.
  #
  # Assets come from GitHub, never the canonical Gitea host, which is reachable
  # only on its own network: a Gitea-hosted download hangs for everyone else.
  desc "Share files, logs, and diffs as short links with provenance and a TTL"
  homepage "https://cairn.stump.wtf"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.4.0/cairn_0.4.0_darwin_arm64.tar.gz"
      sha256 "97c1c11e41f9806033a33d34577c81ba3583bd7cd8ba9f62a84409e9220f20f2"
    end
    on_intel do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.4.0/cairn_0.4.0_darwin_amd64.tar.gz"
      sha256 "7544081275a2dbef75230f280ce33a2ace8a261b1c4fa291aabf9f1be1db9c14"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.4.0/cairn_0.4.0_linux_arm64.tar.gz"
      sha256 "58f8c6e10a07add1ac04f362ee9cff262913e5fb15e7e1b115a8cec8b78efa28"
    end
    on_intel do
      url "https://github.com/stump-wtf/cairn/releases/download/v0.4.0/cairn_0.4.0_linux_amd64.tar.gz"
      sha256 "4ab829afb4ff328c272a299322a8da73c726b893bc9e1f1ecfcdfe29e2c8f083"
    end
  end

  def install
    # The archive holds exactly `cairn` and `LICENSE` at its root
    # (.goreleaser.yaml pins archives.files to [LICENSE] and leaves
    # wrap_in_directory off), so name the binary rather than globbing: a glob
    # would install LICENSE into bin/ as though it were a program.
    bin.install "cairn"
  end

  test do
    # goreleaser stamps the version with no leading "v", so `cairn --version`
    # prints the bare version.
    assert_match version.to_s, shell_output("#{bin}/cairn --version")
  end
end
